# Generated by Django 3.0.4 on 2020-03-15 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20200312_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='비밀번호')),
            ],
            options={
                'verbose_name': '유송커뮤니티 게시판',
                'verbose_name_plural': '유송커뮤니티 게시판',
                'db_table': 'usong_board',
            },
        ),
    ]
