# Generated by Django 3.0.4 on 2020-03-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='content',
            new_name='contents',
        ),
    ]
